# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 05:23
# Generated by Django 1.10 on 2018-07-24 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.IntegerField(default=50)),
                ('attackBonus', models.IntegerField(default=10)),
                ('defenseBonus', models.IntegerField(default=10)),
                ('movementSpeed', models.IntegerField(default=2)),
                ('energyLevel', models.IntegerField(default=10)),
                ('status', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Knight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.IntegerField(default=50)),
                ('attackBonus', models.IntegerField(default=10)),
                ('defenseBonus', models.IntegerField(default=10)),
                ('movementSpeed', models.IntegerField(default=2)),
                ('energyLevel', models.IntegerField(default=10)),
                ('status', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.IntegerField(default=50)),
                ('attackBonus', models.IntegerField(default=10)),
                ('defenseBonus', models.IntegerField(default=10)),
                ('movementSpeed', models.IntegerField(default=2)),
                ('energyLevel', models.IntegerField(default=10)),
                ('status', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('characterType', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.IntegerField(default=50)),
                ('attackBonus', models.IntegerField(default=10)),
                ('defenseBonus', models.IntegerField(default=10)),
                ('movementSpeed', models.IntegerField(default=2)),
                ('energyLevel', models.IntegerField(default=10)),
                ('status', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
            ],
        ),
    ]
