# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bard',
        ),
        migrations.DeleteModel(
            name='Knight',
        ),
        migrations.DeleteModel(
            name='Mage',
        ),
        migrations.DeleteModel(
            name='Rogue',
        ),
    ]
