# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player'),
        ('game', '0002_auto_20180724_1047'),
    ]

    operations = [
    ]
